name = "erenonal-website"
main = "src/worker.js"
compatibility_date = "2024-05-01"
account_id = ""


[site]
bucket = "./out" 

[env.production]
workers_dev = false
zone_id = ""
routes = [
    "erenonal.com/*",
    "www.erenonal.com/*"
]

[env.staging]
workers_dev = true
